### PR TITLE
[JENKINS-26958]: workflow plugin compatibility

### PR DESCRIPTION
**Pull request by ydubreuil**
[JENKINS-26958](https://issues.jenkins-ci.org/browse/JENKINS-26958)

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
:+1:, thanks for taking this. The first priority is making sure that just installing this plugin does not break Workflow jobs. The second priority is letting the plugin do something useful for a Workflow; looks like that partially works, though [this code](https://github.com/ydubreuil/zentimestamp-plugin/blob/fix-JENKINS-26958/src/main/java/hudson/plugins/zentimestamp/ZenTimestampJobProperty.java#L54) may be preventing some plugin features from working.

**Comment by ndeloof** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
:+1: for the classcast fix.
Probably other improvements could be done in another PR, but I'm OK with the merge

**Comment by ydubreuil** [comment]
@jglick You're right, I'm not sure it's a complete fix, I only did some basic testing with this simple workflow  `node { sh "echo \$BUILD_TIMESTAMP" }` which worked.

@gboissinot would you mind merging this PR and cutting a release? Thanks!

**Comment by jglick** [comment]
@ydubreuil by the way a tip: the slightly simpler script would be

``` groovy
node {sh 'echo $BUILD_TIMESTAMP'}
```

(no need for the escape), or

``` groovy
node {echo env.BUILD_TIMESTAMP}
```

(access the variable from Groovy). It is possible that just

``` groovy
echo env.BUILD_TIMESTAMP
```

also works; cannot remember offhand whether `EnvironmentContributor` is called during script initialization or only by `node`.

**Comment by ghost** [comment]
This pull request originates from a CloudBees employee. At CloudBees, we require that all pull requests be
reviewed by other CloudBees employees before we seek to have the change accepted. If you want to find out
more about our process please see [this note](https://github.com/reviewbybees/about)

**Comment by stephenc** [comment]
:bee:

**Comment by stephenc** [comment]
@reviewbybees done

**Comment by ghost** [comment]
This pull request has completed our internal processes and we now respectfully request the maintainers of this repository to consider our proposal contained within this pull request for merging.

**Pull request merged**
